# Generated by Django 4.0.2 on 2022-02-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition_number', models.IntegerField()),
                ('parties', models.CharField(max_length=200)),
                ('assigning_unit', models.CharField(choices=[('bank fraud', 'bank fraud'), ('Economic Governance', 'Economic Governance'), ('Counter', 'Counter-Terrorism and General investigation')], max_length=200)),
                ('connected_cases', models.CharField(max_length=200)),
                ('case_priority', models.CharField(choices=[('case #1', 'case #1')], max_length=200)),
                ('other_contributors', models.CharField(choices=[('legal department', 'legal department'), ('nitda', 'nitda')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('legal', 'legal'), ('investigation', 'investigation'), ('evidence', 'evidence')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('task_priority', models.CharField(max_length=200)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('assign_member', models.CharField(max_length=200)),
            ],
        ),
    ]
